server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
      discovery:
        locator:
          enabled: true

logging:
  level:
    root: INFO
