server:
  port: 9090

spring:
  application:
    name: monitoring-service

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
